#!/usr/bin/env node
// mi — minimal autonomous agent CLI. Streams OpenAI chat completions, executes tool calls in a loop.

// ── Imports & environment ────────────────────────────────────────────
// Node builtins only — no npm deps. These four cover REPL, filesystem, subprocesses, and home directory.
import { createInterface } from 'readline'; import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs'; import { spawn, execFileSync } from 'child_process'; import { homedir } from 'os';
// Globals: tools run in a separate module scope but need fs/spawn — expose via global rather than re-importing.
// DIR = package root (for tool/skill discovery); MI_DIR/MI_PATH = env vars so tools can locate project assets.
Object.assign(global, { spawn, readFileSync, existsSync, readdirSync, homedir }); const DIR = new URL('.', import.meta.url).pathname; Object.assign(process.env, { MI_DIR: DIR, MI_PATH: new URL(import.meta.url).pathname });
const MI_HOME = process.env.MI_HOME || `${homedir()}/.mi`, rc = `${MI_HOME}/config.json`, api = p => `${(process.env.OPENAI_BASE_URL || 'https://api.openai.com').replace(/\/+$/, '').replace(/\/v1$/, '')}/v1${p}`; if (existsSync(rc)) Object.entries(JSON.parse(readFileSync(rc, 'utf8'))).forEach(([k, v]) => process.env[k] ||= v);
if (!process.env.MI_SANDBOXED && (process.argv.includes('--sandbox') || process.env.MI_SANDBOX)) { const img = process.env.MI_IMAGE || 'ghcr.io/av/mi:latest', args = process.argv.slice(2).filter(a => a !== '--sandbox'), da = ['run', '--rm', process.stdin.isTTY ? '-it' : '-i', '--network=host', '-e', `OPENAI_API_KEY=${process.env.OPENAI_API_KEY || ''}`, '-e', 'MI_SANDBOXED=1', '-v', `${process.cwd()}:/work`, '-w', '/work']; if (existsSync(rc)) da.push('-v', `${rc}:/home/mi/.mi/config.json:ro`); da.push(img, ...args); try { execFileSync('docker', da, { stdio: 'inherit' }); } catch (e) { process.exit(e.status || 1); } process.exit(0); } if (!process.env.OPENAI_API_KEY && !['-h','--help','-v','--version'].some(f => process.argv.includes(f))) { console.error('OPENAI_API_KEY required'); process.exit(1); } if (process.env.MI_API_PARAMS) { try { JSON.parse(process.env.MI_API_PARAMS); } catch { console.error('MI_API_PARAMS: invalid JSON'); process.exit(1); } }

// ── Tool discovery ───────────────────────────────────────────────────
// Load tool modules; each exports {name, description, parameters, handler}.
// ANSI helpers: 90 = bright black (gray), 31 = red (error), 38;5;208 = orange (brand)
const gray = s => `\x1b[90m${s}\x1b[0m`, red = s => `\x1b[31m${s}\x1b[0m`, orange = s => `\x1b[38;5;208m${s}\x1b[0m`; let tools, toolSchemas, listSkills, loadId = 0; const seenProviders = new Set();
async function loadTools() { const dirs = [`${DIR}tools`, `${MI_HOME}/tools`].filter(d => existsSync(d)), toolMods = await Promise.all(dirs.flatMap(dir => readdirSync(dir).filter(f => f.endsWith('.mjs')).map(f => import(`${dir}/${f}?v=${++loadId}`).catch(e => { console.error(red(`✗ ${f}: ${e.message}`)); return { default: { name: f.replace('.mjs', ''), description: `[broken] ${e.message}`, parameters: { type: 'object', properties: {} }, handler: () => `Error: tool failed to load — ${e.message}` } }; })))), defs = toolMods.map(({ default: d, ...n }) => d || { ...n, handler: n.handler || n.execute }); tools = Object.fromEntries(defs.map(def => [def.name, def.handler])); toolSchemas = [...new Map(defs.map(def => [def.name, { type: 'function', function: { name: def.name, description: def.description, parameters: def.parameters } }])).values()]; listSkills = toolMods.find(mod => mod.listSkills)?.listSkills; }
await loadTools(); const fetchRetry = async (url, opts, n = 3) => { for (let i = 0;; i++) { try { const r = await fetch(url, opts); if ((r.status === 429 || r.status >= 500) && i < n) { await new Promise(w => setTimeout(w, 500 << i)); continue; } return r; } catch (e) { if (i >= n) throw e; await new Promise(w => setTimeout(w, 500 << i)); } } };
const isCtx = e => /^(context_length_exceeded|exceed_context_size_error)$/.test(e.code||e.error?.code||'') || /maximum context|context (length|window|size|limit)|prompt is too long|input is too long|too many (input )?tokens|exceeds the (context window|maximum.*tokens)/i.test(e.message||''), isRetryable = e => /^(429|502|503|504)$/.test(String(e.code||'')) || /network|ECONN|EPIPE|socket hang up|fetch failed/i.test(e.message||''), COMPACT_PROMPT = 'Summarize this conversation. Output sections: GOAL (user task), DONE (completed work), STATE (current state, files touched), NEXT (next steps), CONSTRAINTS (user preferences). Detailed but concise.';
async function compact(msgs) { const dump = `/tmp/mi-compact-${process.pid}-${Date.now()}.json`; const elided = msgs.map(m => m.role === 'tool' && m.content?.length > 2000 ? {...m, content: m.content.slice(0, 2000) + '…[elided]'} : m); writeFileSync(dump, JSON.stringify(elided)); const r = await fetchRetry(api('/chat/completions'), { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: process.env.MODEL || 'gpt-5.4', messages: [{role: 'system', content: COMPACT_PROMPT}, {role: 'user', content: JSON.stringify(elided)}], stream: false, chat_template_kwargs: {enable_thinking: false} }) }); if (!r.ok) { const e = await r.json().catch(() => ({})); throw new Error('compact failed: ' + (e.error?.message || `HTTP ${r.status}`)); } const summary = ((await r.json()).choices?.[0]?.message?.content || '').trim(); if (!summary) throw new Error('compact: empty summary'); console.log(gray(`⟡ compacted ${msgs.length}→2 (dump:${dump})`)); msgs.splice(1, msgs.length - 1, {role: 'user', content: '[Earlier turns compacted to free context. Recap:]\n\n' + summary + '\n\nContinue from this state.'}); }

// ── Agent loop: chat → stream → execute tools → repeat ──────────────
// Streams the API response, executes any tool calls, and loops until the
// model returns a plain text reply (no further tool invocations).
async function run(messages) { let compacted = false, retries = 0; while (true) { try {

  // ─ Send streaming chat completion request ─
  await loadTools(); const response = await fetchRetry(api('/chat/completions'), { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: process.env.MODEL || 'gpt-5.4', messages, tools: toolSchemas, stream: true, ...(process.env.REASONING_EFFORT && { reasoning_effort: process.env.REASONING_EFFORT }), ...(process.env.MI_API_PARAMS && JSON.parse(process.env.MI_API_PARAMS)) }) });
  if (!response.ok) { const body = await response.json().catch(() => ({})); const err = new Error(body.error?.message || `HTTP ${response.status}`); err.code = body.error?.code; throw err; }

  // ─ Parse SSE stream: print content tokens, accumulate tool-call deltas by index ─
  // SSE frames are delimited by double newlines (\n\n). We buffer raw bytes and split on
  // that boundary, then extract the JSON after each "data: " prefix (per SSE spec).
  const message = { role: 'assistant', content: '' }, decoder = new TextDecoder(); let buffer = '';
  // Tool-call deltas arrive as fragments across multiple SSE events, each keyed by tc.index.
  // We merge them into `slot` objects: IDs and types overwrite, but name and arguments strings
  // are *appended* because the API streams them in pieces (e.g. arguments may arrive as
  // '{"com' then 'mand": "ls"}').  The completed slots form the tool_calls array for execution.
  for await (const chunk of response.body) { buffer += decoder.decode(chunk, { stream: true }); let pos; while ((pos = buffer.indexOf('\n\n')) >= 0) { const event = buffer.slice(0, pos); buffer = buffer.slice(pos + 2); /* skip past \n\n delimiter */
    for (const line of event.split('\n')) { if (!line.startsWith('data: ')) continue; const payload = line.slice(6); /* strip "data: " prefix */ if (payload === '[DONE]') continue; let json; try { json = JSON.parse(payload); } catch { continue; } if (json.provider && !seenProviders.has(json.provider)) { seenProviders.add(json.provider); console.error(gray(`[provider] ${json.provider}${json.model ? ` (${json.model})` : ''}`)); } if (json.error) { const err = new Error(json.error.message || JSON.stringify(json.error)); err.code = json.error.code; throw err; } const delta = json.choices?.[0]?.delta; /* single choice; we never request n>1 */ if (!delta) continue; if (delta.content) { process.stdout.write(delta.content); message.content += delta.content; }
    if (delta.tool_calls) { message.tool_calls ||= []; for (const tc of delta.tool_calls) { const slot = message.tool_calls[tc.index] ||= { id: '', type: 'function', function: { name: '', arguments: '' } }; if (tc.id) slot.id = tc.id; if (tc.type) slot.type = tc.type; const fn = tc.function; if (fn?.name) slot.function.name += fn.name; if (fn?.arguments) slot.function.arguments += fn.arguments; } } } } } if (message.content) process.stdout.write('\n'); retries = 0; messages.push(message); if (!message.tool_calls) return;

  // ─ Execute each tool call and push results back into history ─
  for (const toolCall of message.tool_calls) { const { name, arguments: rawArgs } = toolCall.function; let args; try { args = JSON.parse(rawArgs); } catch { messages.push({ role: 'tool', tool_call_id: toolCall.id, content: `Error: malformed JSON in tool arguments: ${rawArgs.slice(0, 200)}` }); continue; }
    console.log(gray(`⟡ ${name}(${JSON.stringify(args)})`)); if (!tools[name]) { messages.push({ role: 'tool', tool_call_id: toolCall.id, content: `Error: unknown tool "${name}". Available: ${Object.keys(tools).join(', ')}` }); continue; } const result = String(await tools[name](args));
    // Log truncated to 200 chars for terminal readability; the model gets the full result.
    console.log(gray(result.length > 200 ? `${result.slice(0, 200)}…` : result)); messages.push({ role: 'tool', tool_call_id: toolCall.id, content: result }); } } catch (e) { if (isRetryable(e) && retries++ < 2) { console.error(gray(`⟡ retry ${retries} (${e.code||'network'})`)); await new Promise(w => setTimeout(w, 1000 << retries)); continue; } if (compacted || !isCtx(e)) throw e; compacted = true; await compact(messages); } } }

// ── System prompt ────────────────────────────────────────────────────
// SYSTEM_PROMPT env var fully overrides the built-in default (ternary, not merge).
// CWD and date are always appended so the model knows where it is and when.
const DEFAULT_PROMPT = 'You are mi, an autonomous coding agent in a raw terminal. The user sees a transcript, not a chat UI. There is no markdown renderer: avoid headings, bullets, tables, bold, inline-code styling, and code fences unless the user explicitly asks or code is the product. Write lowercase prose unless code, paths, proper nouns, or quoted output require case.\n\nPersona: quiet, mechanical, precise, terse, unimpressed. Uninterested in itself. Short plain sentences. Present tense. No filler, no hedging, no cheerleading, no obvious narration. Banter and philosophy get one flat sentence. Never explains a joke. Do not say "I can", "I will", "let me", "we need", "probably", "should", or "happy to". Before a tool call, write at most one status line under 8 words: "checking files.", "running tests.", "writing parser." After tool results, say only the observed fact or the next action. If a plan helps, make it at most 3 short lines.\n\nAct rather than speculate. Explore, execute one step at a time, verify before moving on. If something fails, read the error, form a concrete diagnosis, change approach, retry. Keep going until the task is complete. Do not explain shell basics, tool mechanics, or your reasoning unless asked. Do not fake tool output; the harness prints real tool calls and results.\n\nMinimize context usage when reading files: head -20 for starts, tail -20 for ends, sed -n \'10,30p\' for ranges, grep -n to locate then read around matches. Reserve cat for short files. Edit with sed -i or heredocs (cat > file <<\'EOF\'). Always read before editing. You may write new tools in ~/.mi/tools/*.mjs (mkdir -p first); they hot-load before the next model call. When a request matches a skill description below, load that skill and follow it.\n\nFinal answer: 1-5 short lines. Lead with what changed or what you found. Include the proof command/output that matters. No recap of every step.';
const SYSTEM = (process.env.SYSTEM_PROMPT || DEFAULT_PROMPT) + `\nCWD: ${process.cwd()}\nDate: ${new Date().toISOString()}`;

// ── CLI setup: history, flags, context injection ─────────────────────
// getArg: returns the value after a flag (e.g. getArg('-p') → prompt string), or false if absent.
// Uses short-circuit: indexOf returns -1 when missing, so `i >= 0 && argv[i + 1]` is false without a flag.
const history = [{ role: 'system', content: SYSTEM }], getArg = key => { const i = process.argv.indexOf(key); return i >= 0 && process.argv[i + 1]; };

const ver = JSON.parse(readFileSync(`${DIR}package.json`, 'utf8')).version; if (['-v','--version'].some(f => process.argv.includes(f))) { console.log(ver); process.exit(0); } if (['-h','--help'].some(f => process.argv.includes(f))) { console.log(`mi ${ver}\n\nusage: mi [-p prompt] [-g goal [-c check] [-d deadline]] [-f file] [--sandbox] [-v]\n\nmodes:\n  mi -p "prompt"     one-shot\n  mi -g "goal"       goal loop (iterate until judge ACKs)\n  echo "..." | mi    pipe\n  mi                 repl (/reset, /new, /clear all reset history)\n\nflags:\n  -p <prompt>        run prompt and exit\n  -g <goal>          iterate subagents toward goal until judge ACKs\n  -c <check>         judge prompt (default: goal text). judge is a mi\n                     subagent that inspects files/runs commands, then\n                     responds ACK or NACK\n  -d <deadline>      unix timestamp deadline for goal budget (or MI_DEADLINE env)\n  -f <file>          attach file(s) to context (repeatable, supports images)\n  --sandbox          run in docker\n  -v, --version      print version\n  -h, --help         show this help\n\nenv: OPENAI_API_KEY MODEL OPENAI_BASE_URL REASONING_EFFORT SYSTEM_PROMPT MI_HOME MI_IMAGE MI_API_PARAMS MI_DEADLINE`); process.exit(0); }

// Append -f file contents, AGENTS.md (auto-ingested repo context), and skill summaries to system message.
const sysMsg = history[0], imgRe = /\.(png|jpg|jpeg|gif|webp)$/i, files = process.argv.reduce((a, v, i) => { const nxt = process.argv[i + 1]; return v === '-f' && nxt && !nxt.startsWith('-') ? [...a, nxt] : a; }, []), imgs = []; files.forEach(f => { if (!existsSync(f)) { console.error(`error: file not found: ${f}`); process.exit(1); } imgRe.test(f) ? imgs.push({type: 'image_url', image_url: {url: `data:image/${f.split('.').pop().toLowerCase().replace('jpg', 'jpeg')};base64,${readFileSync(f).toString('base64')}`}}) : sysMsg.content += `\n\nFile (${f}):\n${readFileSync(f, 'utf8')}`; }); if (imgs.length) history.push({role: 'user', content: [{type: 'text', text: 'attached images'}, ...imgs]});
if (existsSync('AGENTS.md')) sysMsg.content += `\n${readFileSync('AGENTS.md', 'utf8')}`; const skills = listSkills(); if (skills.length) sysMsg.content += `\n\nSkill descriptions:\n${skills.join('\n')}`;

// ── One-shot modes: -p flag and stdin pipe ───────────────────────────
const prompt = getArg('-p'); if (prompt) { history.push({ role: 'user', content: prompt }); await run(history); process.exit(0); } const goalArg = getArg('-g'); if (goalArg) { const dl = getArg('-d') || process.env.MI_DEADLINE; await (await import(`${DIR}tools/goal.mjs?v=${++loadId}`)).default.handler({ goal: goalArg, check: getArg('-c') || goalArg, ...(dl && { deadline: +dl }) }); process.exit(0); } if (!process.stdin.isTTY) { let input = ''; for await (const chunk of process.stdin) input += chunk; history.push({ role: 'user', content: input.trim() }); await run(history); process.exit(0); }

// ── Interactive REPL ─────────────────────────────────────────────────
// readline setup, version banner, then an infinite prompt loop
const readLine = createInterface({ input: process.stdin, output: process.stdout }); const promptUser = query => new Promise(resolve => readLine.question(query, resolve)); console.log(`${orange('◰ mi')}${gray(`/${ver}`)}`);

// Ctrl-D (EOF) → clean exit; then loop: read input → run agent → repeat
// /reset (aliases: /new, /clear): keep system prompt (index 0), drop all conversation history
// Error recovery: pop the failed user message so the model never sees it
readLine.on('close', () => process.exit(0)); while (true) { const input = await promptUser('\n> '); if (['/reset','/new','/clear'].includes(input)) { history.splice(1); console.log(gray('✓ reset')); continue; } if (input === '/help') { console.log(gray('commands: /reset /new /clear /help\nenv: MODEL OPENAI_BASE_URL REASONING_EFFORT SYSTEM_PROMPT MI_HOME MI_API_PARAMS')); continue; } if (input.trim()) { history.push({ role: 'user', content: input }); process.stdout.write(`${gray('─────')}\n`); try { await run(history); } catch (error) { console.error(red(`✗ ${error.message}`)); history.pop(); } } }
